### ISSUE TITLE
broken readme for l10n_cl_electronic_invoicing

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-chile#23]
Hi,

This is a heads-up that the readme is broken for `l10n_cl_electronic_invoicing`.

Remember the only allowed section title underline in readme fragments in the tilde character: `~`.

This is currently not checked by pylint-odoo (it should), but it is detected by the "ocabot merge" command, which is the preferred way to merge PR in OCA.

**Comment by dreispt** [comment]
Since we're bringing up the readme's, I notice repetition in a lot of modules.
I suggest putting that repeated text in the main repo README, and have the specific module README's link to it's Github URL.

**Comment by max3903** [comment]
Module has been split based on #15 and removed.
