### ISSUE TITLE
[RFC] Obligation of emitting the shipping guide in electronic format

### ISSUE THREAD

**Issue by max3903** [OCA/l10n-chile#48]
# References

Deadline: January 17th, 2020
Resources: 
* http://www.sii.cl/preguntas_frecuentes/factura_electronica/001_003_6624.htm

# Impacts

- [x] Actualizar la lista de documentos en l10n_cl_sii_reference
- [x] Actualizar l10n_cl_etd_stock to set the SII Document automatically

**Comment by esfingex** [comment]
hola max, espero te encuentres bien si te puedo ayudar sería bueno

**Comment by max3903** [comment]
Hola @esfingex 

Gracias por contactarnos. Como nos puedes ayudar? Si sabes de programación Python en Odoo o tu contribución seria mas funcional?

**Comment by esfingex** [comment]
@max3903 soy desarrollador odoo hace 5 años, estoy muy feliz de poder conectar contigo, y poder ofrecer mi ayuda para este proyecto. No sé como podemos continuar y como podemos conectarnos para poder trabajar juntos en esto.

**Comment by max3903** [comment]
@esfingex De inmediato, lo que requerimos son los puntos listado en la descripción arriba.

De maneja general, puedes trabajar sobre cualquier issues, por ejemplo:
* la roadmap en #52
* la migracion en #4

**Comment by esfingex** [comment]
sobre toponyms ( #4 ) yo tengo mi propia customización si quieres le puedes echar un ojo o puedo reescribir completa la que hay, no sé cual se mejor opción la verdad.

El plan cuentas en chile, más bien varia según cliente. Tengo algo para eso igual, pero creo que nos faltaría la ayuda de un contador, para un generico mejor diseñado.

**Comment by max3903** [comment]
@esfingex 

Si quieres compartir algo, adelante lo revisamos. Pero no te puedo garantizar que lo vamos a incluir porque ya tenemos algo funcional. Pero si es mejor, a la mejor si.
