### ISSUE TITLE
[RFC] l10n_cl_etd_stock

### ISSUE THREAD

**Issue by max3903** [OCA/l10n-chile#49]
This change will allow the picking to use the folio from the sequence and comply with the changes listed in #48.

# stock.picking

- [x] Set the SII Document field as a read-only field
- [x] Extend the create method to:
* check the partner and its invoicing policy
* if invoicing policy is "Electronic Guide"
  * Set the SII Document field to "Guia de Despacho Electronica"
  * Use the folio on the sequence to generate the document number
* otherwise set the SII Document to False

**Comment by nikitavaghela** [comment]
hello @max3903,  can you help me with this two-line what the actual functionality you want by this
"Set the SII Document field to "Guia de Despacho Electronica"  and "Use the folio on the sequence to generate the document number" 
for now, I searched the SII document by this name "Guia de Despacho Electronica" and set in class_id field of stock_picking. please correct me if it's wrong here.

**Comment by max3903** [comment]
@nikitavaghela 

1. We want to automatically set the "SII Document" field to a specific value "Guia de despacho electronica" if the invoicing_policy of the partner of the picking is "Electronic Guide"

2. With the same conditions, we want to use the folio on the sequence instead of the Odoo normal sequence.

3. You are correct.

CC: @nelsonramirezs

**Comment by nikitavaghela** [comment]
Hello @max3903,
 I checked the sequence folio functionality.
 when picking is creating at that time in sequence we have to configure is_dte is True and need to upload CAF file to generate folio sequence. 
 so as per my knowledge these things are dynamic and depend on configuration.
 please correct me if I'm wrong.
 Can you please send me the reference or demo CAF file for testing?

**Comment by max3903** [comment]
@nikitavaghela You are correct.

@nelsonramirezs Can you provide a demo CAF file?

**Comment by max3903** [comment]
@nikitavaghela I sent the demo CAF file to @murtuzasaleh and @JayVora-SerpentCS this morning.

**Comment by nikitavaghela** [comment]
Hello @max3903, 
I received a demo CAF file. I tried to upload that file but it raised some traceback like [Traceback](https://prnt.sc/qdddb8.) I attached that screenshot it's an error of l10n_cl_sii_folio module. So what I suggest the folio sequence is configuration part so other than that I already committed code. so can you please review that code?

**Comment by max3903** [comment]
@nikitavaghela Please review and merge https://github.com/nikitavaghela/l10n-chile/pull/1
