### ISSUE TITLE
Electronic Guide for Tickets or Individuals. 

### ISSUE THREAD

**Issue by nelsonramirezs** [OCA/l10n-chile#51]
https://github.com/OCA/l10n-chile/blob/9bf29d04dcb5a8e29e4b92bd39442b2cc8ff2826/l10n_cl_invoicing_policy/models/res_partner.py#L29

This policy is correct in theory but not in real life. 

Una Guía de Despacho se emite sólo en dos situaciones:
a) En caso de que las facturas no se emitan al momento de efectuarse la entrega real o simbólica de las especies, los vendedores deberán emitir y entregar al adquirente una Guía de Despacho y, posteriormente (hasta el decimo día del mes siguiente de la operación de venta), emitir la respectiva factura.

b) Cuando se trata de un traslado de especies que no implique una venta.
http://www.sii.cl/preguntas_frecuentes/catastro/001_012_0842.htm

**Comment by nelsonramirezs** [comment]
@max3903 
Hola, Se puede emitir guía de despacho o factura a persona natural que haya realizado inicio de actividades
http://www.sii.cl/preguntas_frecuentes/catastro/001_012_1193.htm

**Comment by max3903** [comment]
@nelsonramirezs It says invoices are for companies. In the other situations (individuals), a ticket must be emitted.
