### ISSUE TITLE
Missing module required

### ISSUE THREAD

**Issue by bluemindsspa** [OCA/l10n-chile#98]
Modules:

- connector_acp
- connector_acp_ftp
- connector_acp_xerox
- l10n_cl_etd
- l10n_cl_account
- l10n_cl_etd_stock
- l10n_cl_etd_xerox
- l10n_cl_etd_xerox_fsmroute

can't be installed because they require a module called "connector" which isn't available

**Comment by max3903** [comment]
You need to get the `connector` module from https://github.com/OCA/connector.
